### ISSUE TITLE
[Bug]: indentation and restOfIndentation don't handle last line correctly

### ISSUE THREAD

**Issue by fsouza** [chrisgrieser/nvim-various-textobjs#21]
### Bug Description

I noticed that there's an edge case not being handled properly in indentation (and restOfIndentation). Around here: https://github.com/chrisgrieser/nvim-various-textobjs/blob/1ede8e289a6acc9202e63b65279b99aaf85d125e/lua/various-textobjs.lua#L330-L332

The way this loop is constructed, the last line is never inspected, leading to an incorrect behavior when considering the last line. For example, consider the example below:

```yaml
object:
  key1: value1
  key2: value2
```

If the cursor is on the second line and I press `vii`, I expect to select the second and the third lines, but it only selects the second line.

It behaves correctly in a case like the following:

```yaml
object:
  key1: value1
  key2: value2
what: ever
```

Since the line number is 1-based, I believe the loop should exit when `nextLnum > lastLine`, whereas currently it exits when `nextLnum == lastLine`.

The annoying side effect with that change is that if the last line is blank, it will be included in the selection:

```yaml
object:
  key1: value1
  key2: value2

```

For that, I think the correct fix is to ignore blank lines at the end of the selection.

### Relevant Screenshot

N/A

### To Reproduce

See description.

### neovim version

```Text
％ nvim --version
NVIM v0.9.0-dev-1222+gf01f18cdf
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.
